# Imperative command equivalent:
# kubectl expose deploy frontend --name=frontend --type=NodePort --port=80 --target-port=8081

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30080   # optional (range: 30000–32767)